# Generated by Django 5.1.3 on 2025-01-10 19:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='Код категорії')),
                ('name', models.CharField(max_length=100, verbose_name="Ім'я категорії")),
                ('image', models.ImageField(blank=True, null=True, upload_to='category/', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Категорія товару',
                'verbose_name_plural': 'Категорії товарів',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='Код товара')),
                ('name', models.CharField(max_length=100)),
                ('main_description', models.TextField(default='Ваш опис', verbose_name='Короткий опис')),
                ('description', models.TextField(verbose_name='Опис')),
                ('price', models.IntegerField(default=0, verbose_name='Ціна')),
                ('quantity', models.IntegerField(default=0, verbose_name='Кількість')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.productcategory', verbose_name='Категорія продукта')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товари',
            },
        ),
    ]
